---
- name: Port State Event from Arista

  hosts: all
  sources:
   - ansible.eda.kafka:
       host: rhel01-nostromo.demoredhat.com
       port: 9092
       topic: network

  rules:
   - name: BGP change detected
     condition: event.body.fields.session_state == "IDLE"
     action:
       run_job_template:
        organization: "Default"
        name: "AI_Enrichment"
        post_events: true
