---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: Malware Advisory
      condition: event.payload.event_type is match("New-Malware")
      action:
        run_workflow_template:
         name: "SC4 - Event Driven Remediation"
         organization: "Globo Financial Service"
         post_events: true
