---
- name: Port State Event from Arista

  hosts: all
  sources:
   - ansible.eda.kafka:
       host: containers.ansible-automates.co.za
       port: 9092
       topic: network

  rules:
   - name: Port is down
     condition: event.body.fields.admin_status == "DOWN"
     action:
       run_job_template:
        organization: "Default"
        name: "Desired port status"
