---
- name: Port State Event from Arista
  hosts: all
  sources:
   - ansible.eda.kafka:
       host: containers.ansible-automates.co.za
       port: 9092
       topic: network

  rules:
    - name: Retrieve Data and Launch Job-template
      condition: events.body.fields.new_state == "interface-notif-state-down" and events.body.fields.if_name in vars.protected
      action:
        run_job_template:
          name: "EDA-Fix-Ports"
          organization: "Default"
          job_args:
            extra_vars:
              interface: "{{ event.body.fields.if_name }}"
              rtr: "{{ event.body.fields.host_name }}"
