---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002

  rules:

    - name: Tenable Advisory
      condition: event.payload.event_type is match("new-tenable")
      action:
        run_workflow_template:
         name: "SC4 - Tenable Event"
         organization: "Globo Financial Service"
         post_events: true
