---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
  - name: VLAN created event
    condition:
      all:
        - event.payload.event == "created"
        - event.payload.model == "vlan"
    action:
      run_job_template:
        organization: "Default"
        name: "Create VLAN"
