---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: Tenable Advisory
      condition: event.payload.event is match("created")
      action:
        run_job_template:
          organization: "Default"
          name: "Desired port status"
