---
- name: Make API Call to ChatGPT/LLM
  hosts: localhost
  vars:
    _url_: https://api.openai.com/v1/completions
    api_key: 
    gpt_model: "gpt-3.5-turbo-instruct"
    gpt_prompt: "Please explain this Windows Event: {{ ansible_eda.event.body.winlog.event_id }} "
    SN_USERNAME:
    SN_PASSWORD:
    SN_HOST:

  tasks:
    - name: Send API request to ChatGPT/LLM
      uri:
        url: "{{ _url_ }}"
        method: POST
        headers: 
         Content-Type: application/json
         Authorization: Bearer {{ api_key }}
        body_format: json
        body:
          model: "{{ gpt_model }}"
          prompt: "{{ gpt_prompt }}"
          max_tokens: 100  # Adjust the max_tokens as needed
      register: api_response

    - name: Extract text from API response
      set_fact:
        response_text: "{{ api_response.json.choices[0].text }}"

    - name: Display extracted text
      debug:
        var: response_text
