- name: Basic Troubleshooting BGP
  hosts: ceos1
  gather_facts: false
  vars:
    switches:
      - ping 10.0.0.1
      - ping 10.0.0.4

  tasks:

    - name: BGP Check
      arista.eos.eos_command:
       commands: show ip bgp summary vrf all
      register: bgp_summary

    - name: Check reachability of switches
      arista.eos.eos_command:
       commands: "{{ switches }}"
      register: result

    - set_fact:
       cacheable: true
       bgp_view: "{{ bgp_summary }}"
       bgp_ping: "{{ result }}"
       status: done
       bgp_state: "{{ ansible_eda.event.body.fields.session_state }}"
       bgp_prob_neighbor: "{{ ansible_eda.event.body.tags.neighbor_address }}"
      
    - name: Send notification message via Mattermost
      community.general.mattermost:
       url: http://containers.ansible-automates.co.za:8065
       api_key: "{{ api_token }}"
       attachments:
         - text: "!!!!!! ALERT !!!!!!"
           color: '#ff00dd'
           title: BGP ERROR
           fields:
            - title: Issue Detected
              value: "BGP Session: {{ ansible_eda.event.bgp_state }}"
              short: true
            - title: Potential Problem
              value: "Problematic node/path: {{ ansible_eda.event.bgp_prob_neighbor }}"
              short: true
            - title: Message
              value: "Event detected issue, human intervention is required, Dave"
              short: true
      delegate_to: localhost
