---
- hosts: localhost
  gather_facts: false
  connection: httpapi
  vars:
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    SN_HOST: "{{ lookup('env', 'SN_HOST') }}"
    SN_USERNAME: "{{ lookup('env', 'SN_USERNAME') }}"
    SN_PASSWORD: "{{ lookup('env', 'SN_PASSWORD') }}"
    
  tasks:

  - name: Create incident
    servicenow.itsm.incident:
     instance:
      host: "{{ SN_HOST }}"
      username: "{{ SN_USERNAME }}"
      password: "{{ SN_PASSWORD }}"
     state: new
     caller: "{{ lookup('env', 'SN_USERNAME') }}"
     short_description: "TEST"
     description: "Network configurations have been backed up and uploaded"
     impact: high
     urgency: high
    delegate_to: localhost
